apiVersion: v1
kind: Service
metadata:
  name: bolig-identity-server-service
spec:
  selector:
    app: bolig-identity-server
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 54341